version: '3.4'

services:
  blank-docker-node.project:
    image: blank-docker-node.project
    build:
      context: .
      dockerfile: ./Dockerfile
    environment:
      NODE_ENV: production
    ports:
      - 3000:3000